In [2]:
import pandas as pd 
import numpy as np

In [4]:
balance_df = pd.read_csv("../Obtencion datos/balance_electrico.csv")

balance_df

,Unnamed: 0,nombre,tipo de energía,Valores,Porcentaje,Fecha actualización
0,0,Renewable generation,Renewable,283293.8550,1,28/07/2022
1,1,Renewable generation,Renewable,315791.7010,1,29/07/2022
2,2,Renewable generation,Renewable,358667.5460,1,30/07/2022
3,3,Renewable generation,Renewable,312348.7135,1,31/07/2022
4,4,Renewable generation,Renewable,306444.6200,1,01/08/2022
...,...,...,...,...,...,...
178,178,Demand at busbars,Demand at busbars,695597.3890,1,22/09/2022
179,179,Demand at busbars,Demand at busbars,689988.5230,1,23/09/2022
180,180,Demand at busbars,Demand at busbars,602468.7460,1,24/09/2022
181,181,Demand at busbars,Demand at busbars,547492.9340,1,25/09/2022
182,182,Demand at busbars,Demand at busbars,638740.3510,1,26/09/2022